
all: insertion selection bubble

insertion: insertion_tester.c Insertion/insertion_sort.c
	gcc -o insertion_tester insertion_tester.c Insertion/insertion_sort.c -I./Insertion/

selection: selection_tester.c Selection/selection_sort.c
	gcc -o selection_tester selection_tester.c Selection/selection_sort.c -I./Selection/

bubble: bubble_tester.c Bubble/bubble_sort.c
	gcc -o bubble_tester bubble_tester.c Bubble/bubble_sort.c -I./Bubble/
